import os
import torch
import torch.nn as nn
import streamlit as st
from PIL import Image
from models.pneumonia_net import PneumoniaNet
from transformations.pneumonia import test_transforms as pneumonia_tf

# ========== DEVICE ==========
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")


# ========== MODEL LOADERS ==========

@st.cache_resource
def load_pneumonia_model():
    weights_path = os.path.join("weights", "best_pneumonia_net.pth")
    model = PneumoniaNet().to(device)
    state = torch.load(weights_path, map_location=device)
    model.load_state_dict(state)
    model.eval()
    return model

# ========== PREDICTION GENERICA ==========

def predict_image(img_pil: Image.Image,
                  model: nn.Module,
                  transform,
                  pos_label: str,
                  neg_label: str):

    # Se i transform BraTS/X-ray partono da grayscale o RGB gestiscilo qui
    x = transform(img_pil).unsqueeze(0).to(device)

    with torch.no_grad():
        logit = model(x).squeeze()
        prob = torch.sigmoid(logit).item()

    label = pos_label if prob >= 0.5 else neg_label
    return label, prob



# pdf
import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from datetime import datetime


#PDF
def build_pdf_report(img_pil, label, prob, model_info: dict) -> bytes:

    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Margini
    margin_x = 50
    y = height - 50

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin_x, y, "Pneumonia Detection – Model Report")
    y -= 20
    c.setFont("Helvetica", 10)
    c.drawString(margin_x, y, f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y -= 30

    # Immagine (thumbnail)
    # riduco l'immagine
    img_copy = img_pil.copy()
    img_copy.thumbnail((300, 300))
    img_reader = ImageReader(img_copy)

    img_x = margin_x
    img_y = y - 300
    c.drawImage(img_reader, img_x, img_y, width=200, height=200, preserveAspectRatio=True, mask='auto')

    # Risultato a destra
    text_x = img_x
    text_y = y

    c.setFont("Helvetica-Bold", 12)
    c.drawString(text_x, text_y, "Prediction")
    text_y -= 20
    c.setFont("Helvetica", 11)
    c.drawString(text_x, text_y, f"Predicted class: {label.upper()}")
    text_y -= 15
    c.drawString(text_x, text_y, f"P(pneumonia): {prob:.4f}")
    text_y -= 20

    # Confidence level
    if prob >= 0.8:
        conf = "High"
    elif prob >= 0.5:
        conf = "Medium"
    else:
        conf = "Low"

    c.drawString(text_x, text_y, f"Model confidence: {conf}")
    text_y -= 30

    # Model info
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, img_y - 30, "Model details")
    c.setFont("Helvetica", 10)
    info_y = img_y - 45

    for k, v in model_info.items():
        c.drawString(margin_x, info_y, f"- {k}: {v}")
        info_y -= 12

    # Disclaimer
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin_x, 80, "Disclaimer")
    c.setFont("Helvetica", 9)
    c.drawString(margin_x, 65, "This report is generated by a research prototype model and is NOT a medical device.")
    c.drawString(margin_x, 52, "Predictions must not be used for diagnosis or treatment decisions.")

    c.showPage()
    c.save()

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

# ========== UI ==========
def set_progressbar_color(color):
    st.markdown(
        f"""
        <style>
        .stProgress > div > div > div > div {{
            background-color: {color};
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

def main():
    st.set_page_config(page_title="Medical Imaging Classifier", layout="wide")
    kaggle_url = "https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia"
    st.title("Medical Imaging Classifier")
    st.write(
        "- **Pneumonia (X-ray)** usa il modello PneumoniaNet addestrato sul dataset chest_xray di Kaggle.\n"
        f"- Link del dataset: {kaggle_url} \n"
        "- Questo strumento è a solo scopo accademico e **non sostituisce un referto medico.**"
    )

    with st.expander("🔍 Informazioni sul Modello — PneumoniaNet"):
        st.markdown("""
        <div style="
            padding: 18px;
            border-radius: 12px;
            background-color: #1e1e1e;
            color: #f2f2f2;
            border: 1px solid #333;
            line-height: 1.45;
        ">

        <h2 style='color:#58a6ff;'>🧠 Panoramica del Modello</h2>
        <p>
        <b>PneumoniaNet</b> è una rete neurale convoluzionale progettata per classificare radiografie del torace
        in due categorie: <b>Normale</b> e <b>Polmonite</b>.
        </p>

        <hr style="border: 1px solid #444;">

        <h3 style='color:#ffdd57;'>🏗️ Architettura</h3>
        <ul>
            <li>4 blocchi convoluzionali: <b>16 → 32 → 64 → 128 filtri</b></li>
            <li>Batch Normalization in ogni blocco</li>
            <li>MaxPooling dopo ogni blocco</li>
            <li>Adaptive Global Average Pooling</li>
            <li>Fully Connected finale: <b>128 → 64 → 1</b></li>
            <li>Dropout <b>0.5</b> per ridurre overfitting</li>
        </ul>
        <p><b>Input:</b> radiografia in scala di grigi 1×224×224</p>

        <hr style="border: 1px solid #444;">

        <h3 style='color:#7ee787;'>📚 Dataset</h3>
        <p>
        Dataset “Chest X-Ray Pneumonia” di Kaggle.  
        Classi disponibili: <b>Normale</b>, <b>Polmonite</b>.  
        Immagini reali, con suddivisione train/val/test già fornita.
        </p>

        <hr style="border: 1px solid #444;">

        <h3 style='color:#ffa657;'>⚙️ Parametri di Addestramento</h3>
        <ul>
            <li>Loss: <b>BCEWithLogitsLoss</b></li>
            <li>Ottimizzatore: <b>Adam (lr=3e-4)</b></li>
            <li>Epoche: 30 con <b>Early Stopping (patience = 5)</b></li>
            <li>Data augmentation:
                <ul>
                    <li>Horizontal Flip</li>
                    <li>Rotazione casuale (±7°)</li>
                </ul>
            </li>
            <li>Normalizzazione: mean = 0.5, std = 0.5</li>
        </ul>

        <hr style="border: 1px solid #444;">

        <h3 style='color:#d2a8ff;'>📈 Prestazioni</h3>
        <p><b>Accuratezza:</b> 88%  
           <b>ROC-AUC:</b> 0.95  
           <b>F1-Score:</b>
        </p>
        <ul>
            <li>Normale: <b>0.84</b></li>
            <li>Polmonite: <b>0.90</b></li>
        </ul>

        <hr style="border: 1px solid #444;">

        <h3 style='color:#f85149;'>⚠️ Limitazioni</h3>
        <ul>
            <li>Non è un dispositivo medico</li>
            <li>Generalizzazione limitata: immagini provenienti da ospedali diversi possono variare</li>
            <li>Funziona solo su radiografie frontali del torace</li>
        </ul>

        </div>
        """, unsafe_allow_html=True)

    st.markdown(f"*Device in uso:* `{device}`")


    uploaded_file = st.file_uploader(
        "Carica un'immagine (JPG/PNG)", type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is None:
        st.info("Carica un'immagine per ottenere una predizione.")
        return

    img_bytes = uploaded_file.read()
    img_pil = Image.open(io.BytesIO(img_bytes))


    model = load_pneumonia_model()
    transform = pneumonia_tf
    pos_name = "pneumonia"
    neg_name = "normal"


    label, prob = predict_image(img_pil, model, transform, pos_name, neg_name)

    col1, col2 = st.columns([2, 1])

    model_info = {
        "Architecture": "Custom CNN (4 conv blocks + GAP)",
        "Input": "1x224x224 chest X-ray",
        "Test accuracy": "0.88",
        "ROC-AUC": "0.95",
    }

    pdf_bytes = build_pdf_report(img_pil, label, prob, model_info)

    with col1:
        st.image(img_pil, caption="Input image")

    with col2:
        st.subheader("Prediction")
        st.write(f"**Class:** `{label}`")
        prob = prob * 100
        st.write(f"**P({pos_name}):** `{prob:.2f}%`")
        set_progressbar_color("#00C853")
        st.progress(prob/100)

        if label == pos_name:
            st.warning(f"- Il modello suggerisce **{pos_name}**.\n - Non è un referto medico.")
        else:
            st.info(f"- Il modello suggerisce **{neg_name}**.\n - Non è un referto medico.")
        st.download_button(
            label="📄 Download PDF report",
            data=pdf_bytes,
            file_name="pneumonia_report.pdf",
            mime="application/pdf",
        )


if __name__ == "__main__":
    main()